//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNHMVC.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FNHMVC.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is exists.
        /// </summary>
        internal static string CategoryExists {
            get {
                return ResourceManager.GetString("CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal existe.
        /// </summary>
        internal static string CodigoPostalExist {
            get {
                return ResourceManager.GetString("CodigoPostalExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal y Localidad existe.
        /// </summary>
        internal static string CodigoPostalLocalidadExist {
            get {
                return ResourceManager.GetString("CodigoPostalLocalidadExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario existe.
        /// </summary>
        internal static string ComentarioExists {
            get {
                return ResourceManager.GetString("ComentarioExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa existe.
        /// </summary>
        internal static string EmpresaExist {
            get {
                return ResourceManager.GetString("EmpresaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad existe.
        /// </summary>
        internal static string LocalidadExist {
            get {
                return ResourceManager.GetString("LocalidadExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca existe.
        /// </summary>
        internal static string MarcaExist {
            get {
                return ResourceManager.GetString("MarcaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje existe.
        /// </summary>
        internal static string MensajeExist {
            get {
                return ResourceManager.GetString("MensajeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo existe.
        /// </summary>
        internal static string ModeloExist {
            get {
                return ResourceManager.GetString("ModeloExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticia existe.
        /// </summary>
        internal static string NoticiaExist {
            get {
                return ResourceManager.GetString("NoticiaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais existe.
        /// </summary>
        internal static string PaisExist {
            get {
                return ResourceManager.GetString("PaisExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona existe.
        /// </summary>
        internal static string PersonaExist {
            get {
                return ResourceManager.GetString("PersonaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto existe.
        /// </summary>
        internal static string ProductoExists {
            get {
                return ResourceManager.GetString("ProductoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia existe.
        /// </summary>
        internal static string ProvinciaExist {
            get {
                return ResourceManager.GetString("ProvinciaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo via existe.
        /// </summary>
        internal static string TipoViaExist {
            get {
                return ResourceManager.GetString("TipoViaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is exists.
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario existe.
        /// </summary>
        internal static string UsuarioExist {
            get {
                return ResourceManager.GetString("UsuarioExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión existe.
        /// </summary>
        internal static string VersionExist {
            get {
                return ResourceManager.GetString("VersionExist", resourceCulture);
            }
        }
    }
}
